### ISSUE TITLE
Is it can be used for .msg.22 which is from RE4?

### ISSUE THREAD

**Issue by MotokaJuu** [dtlnor/RE_MSG#2]
![image](https://github.com/dtlnor/RE_MSG/assets/126642398/6de7077a-297b-4854-ae0f-c17d13d93967)

**Comment by dtlnor** [comment]
> ![image](https://github.com/dtlnor/RE_MSG/assets/126642398/6de7077a-297b-4854-ae0f-c17d13d93967)
> 
> 

it should be. if you want to use it, you may try to change your encoding setting

if you want to do mod, I suggest you use remsg converter

**Comment by MotokaJuu** [comment]
choose utf-8 can't deal with it. anyway i'll try remsg converter
